services:
  db:
    image: postgres:16
    container_name: trivy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trivy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: trivy-report-serializer-app
    container_name: trivy-report-serializer-app
    build:
      context: .
      dockerfile: dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/trivy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

volumes:
  pgdata:
