replicaCount: 1

image:
  repository: mushroomhat/startrack
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: env
    value: production
  - name: site
    value: local
  - name: sla_days
    value: "90"
  - name: mode
    value: non-hub
  - name: hub_url
    value: http://localhost:80

  # - name: LOG_LEVEL
  #   value: info
