#https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml

image:
  registry: docker.io
  repository: dpage/pgadmin4
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9.11.0"

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false

existingSecret: pgadmin4
env:
  # can be email or nickname
  email: starforge@test.com
