name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Set up Docker Buildx (better caching + multi arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/trivy-report-serializer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/trivy-report-serializer:${{ github.sha }}

      # --- Optional: post-build info
      - name: Image pushed
        run: echo "Docker image successfully pushed!"
